suppressionDuration: 5h
queryPeriod: 30m
kind: Scheduled
version: 1.0.0
tactics:
- CredentialAccess
- Persistence
description: |-
  A new secret was added to an high privileged application.

  Can contain false positives if a secret was deleted but there is still another secret present
entityMappings:
- entityType: Account
  fieldMappings:
  - identifier: FullName
    columnName: AccountCustomEntity
- entityType: IP
  fieldMappings:
  - identifier: Address
    columnName: IPCustomEntity
suppressionEnabled: false
queryFrequency: 30m
triggerOperator: gt
name: 'Secret added to high privileged application'
triggerThreshold: 0
query: |+
  // Needs custom watchlist HighRiskApps
  // Must contain objectId, name of all high priv apps (manual process)
  // objectId must be SearchKey
  AuditLogs
  | where OperationName has_any ("Add service principal", "Certificates and secrets management")
  | where Result =~ "success"
  | where tostring(InitiatedBy.user.userPrincipalName) has "@" or tostring(InitiatedBy.app.name) has "@"
  | extend targetname = tostring(TargetResources[0].name)
  | extend targetId = tostring(TargetResources[0].id)
  | extend targetType = tostring(TargetResources[0].type)
  | extend keyEvents = TargetResources[0].modifiedProperties
  | mv-expand keyEvents
  | where keyEvents.name =~ "KeyDescription"
  | extend new_value_set = parse_json(tostring(keyEvents.newValue))
  | extend old_value_set = parse_json(tostring(keyEvents.oldValue))
  | where old_value_set == "[]"
  | mv-expand new_value_set
  | parse new_value_set with * "KeyIdentifier=" keyIdentifier:string ",KeyType=" keyType:string ",KeyUsage=" keyUsage:string ",name=" keyname:string "]" *
  | where keyUsage in ("Verify","")
  | extend UserAgent = iff(AdditionalDetails[0].key == "User-Agent",tostring(AdditionalDetails[0].value),"")
  | extend InitiatingUserOrApp = iff(isnotempty(InitiatedBy.user.userPrincipalName),tostring(InitiatedBy.user.userPrincipalName), tostring(InitiatedBy.app.name))
  | extend InitiatingIpAddress = iff(isnotempty(InitiatedBy.user.ipAddress), tostring(InitiatedBy.user.ipAddress), tostring(InitiatedBy.app.ipAddress))
  | project-away new_value_set, old_value_set
  | project-reorder TimeGenerated, OperationName, InitiatingUserOrApp, InitiatingIpAddress, UserAgent, targetname, targetId, targetType, keyname, keyType, keyUsage, keyIdentifier, CorrelationId, TenantId
  | join kind=inner _GetWatchlist('HighRiskApps') on $left.targetId == $right.SearchKey
  | extend timestamp = TimeGenerated, AccountCustomEntity = InitiatingUserOrApp, IPCustomEntity = InitiatingIpAddress
enabled: true
id: 5d5dfb1e-29d8-4568-bfa3-f7e4caad5162
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: 5h
    matchingMethod: AllEntities
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails: []
eventGroupingSettings:
  aggregationKind: AlertPerResult
customDetails:
  Application: targetname
  SecretTypeAdded: keyType
severity: High

